- name: Install packages.
  apt:
      name: "{{item}}"
      update_cache: true
  sudo: true
  with_items:
  - build-essential
  - qt-sdk
  - libqt5webkit5-dev
  - libpq-dev
  - imagemagick
  - libcurl3
  - libcurl3-gnutls
  - libcurl4-openssl-dev
  - ruby-dev
  - nodejs
  - xvfb